// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v4.24.0
// source: gm.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SGm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int32                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SGm) Reset() {
	*x = C2SGm{}
	mi := &file_gm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SGm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SGm) ProtoMessage() {}

func (x *C2SGm) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SGm.ProtoReflect.Descriptor instead.
func (*C2SGm) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{0}
}

func (x *C2SGm) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *C2SGm) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *C2SGm) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *C2SGm) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type S2CGm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	No            int32                  `protobuf:"varint,1,opt,name=no,proto3" json:"no,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Remote        string                 `protobuf:"bytes,4,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CGm) Reset() {
	*x = S2CGm{}
	mi := &file_gm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CGm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CGm) ProtoMessage() {}

func (x *S2CGm) ProtoReflect() protoreflect.Message {
	mi := &file_gm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CGm.ProtoReflect.Descriptor instead.
func (*S2CGm) Descriptor() ([]byte, []int) {
	return file_gm_proto_rawDescGZIP(), []int{1}
}

func (x *S2CGm) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *S2CGm) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S2CGm) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *S2CGm) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

var File_gm_proto protoreflect.FileDescriptor

var file_gm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x6d, 0x22, 0xac, 0x01, 0x0a, 0x05, 0x43, 0x32, 0x53, 0x47,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6e,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x6d, 0x2e, 0x43, 0x32, 0x53, 0x47, 0x6d, 0x2e, 0x41, 0x72,
	0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x1a, 0x37, 0x0a,
	0x09, 0x41, 0x72, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5b, 0x0a, 0x05, 0x53, 0x32, 0x43, 0x47, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6e, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gm_proto_rawDescOnce sync.Once
	file_gm_proto_rawDescData = file_gm_proto_rawDesc
)

func file_gm_proto_rawDescGZIP() []byte {
	file_gm_proto_rawDescOnce.Do(func() {
		file_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_gm_proto_rawDescData)
	})
	return file_gm_proto_rawDescData
}

var file_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gm_proto_goTypes = []any{
	(*C2SGm)(nil), // 0: protocol.gm.C2SGm
	(*S2CGm)(nil), // 1: protocol.gm.S2CGm
	nil,           // 2: protocol.gm.C2SGm.ArgsEntry
}
var file_gm_proto_depIdxs = []int32{
	2, // 0: protocol.gm.C2SGm.args:type_name -> protocol.gm.C2SGm.ArgsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gm_proto_init() }
func file_gm_proto_init() {
	if File_gm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gm_proto_goTypes,
		DependencyIndexes: file_gm_proto_depIdxs,
		MessageInfos:      file_gm_proto_msgTypes,
	}.Build()
	File_gm_proto = out.File
	file_gm_proto_rawDesc = nil
	file_gm_proto_goTypes = nil
	file_gm_proto_depIdxs = nil
}
