# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leaderboard.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11leaderboard.proto\x12\x14protocol.leaderboard\"Y\n\x13\x43\x32SQueryLeaderboard\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x66rom\x18\x04 \x01(\x05\x12\n\n\x02to\x18\x05 \x01(\x05\"=\n\x13S2CQueryLeaderboard\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leaderboard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_C2SQUERYLEADERBOARD']._serialized_start=43
  _globals['_C2SQUERYLEADERBOARD']._serialized_end=132
  _globals['_S2CQUERYLEADERBOARD']._serialized_start=134
  _globals['_S2CQUERYLEADERBOARD']._serialized_end=195
# @@protoc_insertion_point(module_scope)
