# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x0eprotocol.login\" \n\x12\x43\x32SQueryServerList\x12\n\n\x02no\x18\x01 \x01(\x05\"<\n\x12S2CQueryServerList\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"8\n\x08\x43\x32SLogin\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x10\n\x08serverId\x18\x03 \x01(\t\"4\n\x08S2CLogin\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0e\n\x06userId\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_C2SQUERYSERVERLIST']._serialized_start=31
  _globals['_C2SQUERYSERVERLIST']._serialized_end=63
  _globals['_S2CQUERYSERVERLIST']._serialized_start=65
  _globals['_S2CQUERYSERVERLIST']._serialized_end=125
  _globals['_C2SLOGIN']._serialized_start=127
  _globals['_C2SLOGIN']._serialized_end=183
  _globals['_S2CLOGIN']._serialized_start=185
  _globals['_S2CLOGIN']._serialized_end=237
# @@protoc_insertion_point(module_scope)
