# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gm_pb2 as gm__pb2
import heartbeat_pb2 as heartbeat__pb2
import leaderboard_pb2 as leaderboard__pb2
import login_pb2 as login__pb2
import query_pb2 as query__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x08protocol\x1a\x08gm.proto\x1a\x0fheartbeat.proto\x1a\x11leaderboard.proto\x1a\x0blogin.proto\x1a\x0bquery.proto\"\x83\x07\n\x0eMessageWrapper\x12%\n\x06\x63\x32s_gm\x18\xe9\x07 \x01(\x0b\x32\x12.protocol.gm.C2SGmH\x00\x12%\n\x06s2c_gm\x18\xea\x07 \x01(\x0b\x32\x12.protocol.gm.S2CGmH\x00\x12:\n\rc2s_heartbeat\x18\xeb\x07 \x01(\x0b\x32 .protocol.heartbeat.C2SHeartbeatH\x00\x12:\n\rs2c_heartbeat\x18\xec\x07 \x01(\x0b\x32 .protocol.heartbeat.S2CHeartbeatH\x00\x12K\n\x15\x63\x32s_query_leaderboard\x18\xed\x07 \x01(\x0b\x32).protocol.leaderboard.C2SQueryLeaderboardH\x00\x12K\n\x15s2c_query_leaderboard\x18\xee\x07 \x01(\x0b\x32).protocol.leaderboard.S2CQueryLeaderboardH\x00\x12\x44\n\x15\x63\x32s_query_server_list\x18\xef\x07 \x01(\x0b\x32\".protocol.login.C2SQueryServerListH\x00\x12\x44\n\x15s2c_query_server_list\x18\xf0\x07 \x01(\x0b\x32\".protocol.login.S2CQueryServerListH\x00\x12.\n\tc2s_login\x18\xf1\x07 \x01(\x0b\x32\x18.protocol.login.C2SLoginH\x00\x12.\n\ts2c_login\x18\xf2\x07 \x01(\x0b\x32\x18.protocol.login.S2CLoginH\x00\x12\x44\n\x15\x63\x32s_query_player_data\x18\xf3\x07 \x01(\x0b\x32\".protocol.query.C2SQueryPlayerDataH\x00\x12\x44\n\x15s2c_query_player_data\x18\xf4\x07 \x01(\x0b\x32\".protocol.query.S2CQueryPlayerDataH\x00\x12\x46\n\x16\x63\x32s_query_player_basic\x18\xf5\x07 \x01(\x0b\x32#.protocol.query.C2SQueryPlayerBasicH\x00\x12\x46\n\x16s2c_query_player_basic\x18\xf6\x07 \x01(\x0b\x32#.protocol.query.S2CQueryPlayerBasicH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEWRAPPER']._serialized_start=100
  _globals['_MESSAGEWRAPPER']._serialized_end=999
# @@protoc_insertion_point(module_scope)
