# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x0eprotocol.query\"0\n\x12\x43\x32SQueryPlayerData\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\t\"\xa7\x01\n\x12S2CQueryPlayerData\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12:\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32,.protocol.query.S2CQueryPlayerData.DataEntry\x12\x0e\n\x06remote\x18\x04 \x01(\t\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x13\x43\x32SQueryPlayerBasic\x12\n\n\x02no\x18\x01 \x01(\x05\x12\r\n\x05users\x18\x02 \x03(\t\"M\n\x13S2CQueryPlayerBasic\x12\n\n\x02no\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x0e\n\x06remote\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _S2CQUERYPLAYERDATA_DATAENTRY._options = None
  _S2CQUERYPLAYERDATA_DATAENTRY._serialized_options = b'8\001'
  _globals['_C2SQUERYPLAYERDATA']._serialized_start=31
  _globals['_C2SQUERYPLAYERDATA']._serialized_end=79
  _globals['_S2CQUERYPLAYERDATA']._serialized_start=82
  _globals['_S2CQUERYPLAYERDATA']._serialized_end=249
  _globals['_S2CQUERYPLAYERDATA_DATAENTRY']._serialized_start=206
  _globals['_S2CQUERYPLAYERDATA_DATAENTRY']._serialized_end=249
  _globals['_C2SQUERYPLAYERBASIC']._serialized_start=251
  _globals['_C2SQUERYPLAYERBASIC']._serialized_end=299
  _globals['_S2CQUERYPLAYERBASIC']._serialized_start=301
  _globals['_S2CQUERYPLAYERBASIC']._serialized_end=378
# @@protoc_insertion_point(module_scope)
